# Generated by Django 3.2 on 2021-04-22 12:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210422_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Isbin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_title', models.CharField(max_length=50)),
                ('booknumber', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='metrics',
        ),
        migrations.DeleteModel(
            name='Metric',
        ),
        migrations.AddField(
            model_name='book',
            name='isbin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.isbin'),
        ),
    ]
