# Generated by Django 3.2 on 2021-04-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210422_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='title',
        ),
        migrations.AddField(
            model_name='isbin',
            name='book_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
