# Generated by Django 3.2 on 2021-04-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20210422_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isbin',
            name='book_title',
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
